Fix `TypeError: camelCase_1.default is not a function` error and fix typo
- For importing some portion of lodash components only, `import ... = require('lodash/...')` statement is needed.
  - Not working with these statements: `import * as ... from 'lodash/...'` or `import ... from 'lodash/...'`
- `typings` => `types` in `package.json`

ref: https://github.com/lodash/lodash/issues/3542#issuecomment-360376983